.TH FAU201-VOLT 1
.SH NAME
fau201-volt \- set FAU201 Power Supply voltage to a given value
.SH SYNOPSIS
.B fau201-volt
.I VOLTAGE
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B fau201-volt
sets the output voltage to the value given in the argument. This value is
expressed in V and must be between 0 and 4.095, inclusive. Decimal values are
accepted.

Specifying a serial number is optional.
.SH EXAMPLE
.TP
.B fau201-volt 1.25
Set the output voltage to 1.25V.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur, or two in case of bad input.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
fau201-clear(1), fau201-info(1), fau201-list(1), fau201-lockotp(1),
fau201-reset(1)
