.TH FAU201-LIST 1
.SH NAME
fau201-list \- list connected FAU201 Power Supply devices
.SH SYNOPSIS
.B fau201-list
.SH DESCRIPTION
.B fau201-list
lists all power supply devices that are currently connected. Note that the
first device on the list is always the one addressed by default. Hence, when
applicable, a command invoked without any serial number specified will always
take effect on that device.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
fau201-clear(1), fau201-info(1), fau201-lockotp(1), fau201-reset(1),
fau201-volt(1)
